name: flutter_ieadi_app
description: Aplicativo de igreja.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  enum_to_string: ^2.0.1
  meta: ^1.3.0
  cloud_firestore: ^2.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  equatable: ^2.0.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  intl: ^0.17.0
  timeago: ^3.1.0
  uuid: ^3.0.4
  flutter_feather_icons: ^2.0.0+1
  badges: ^2.0.1
  google_fonts: ^2.1.0
  nanoid: ^1.0.0
  provider: ^5.0.0
  mask_text_input_formatter: ^2.0.0
  brasil_fields: ^1.1.4
  sizer: ^2.0.13
  pdf: ^3.4.2
  advance_pdf_viewer: ^2.0.0
  share_extend: ^2.0.0
  flutter_launcher_icons: ^0.9.1
  printing: ^5.4.3
  
advance_pdf_viewer: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

#dependency_overrides:
  #intl: ^0.17.0
  #crypto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
    - user.jpeg
    - logo01.png
    - logo02.png
    - cartao_m.png
    - cartao_m_verso.png
    - logo_novo.png
    - certificado.png
    - assinatura.png
    - batismo.jpg
    - OpenSans-Light.ttf
    - OpenSans-Regular.ttf
    - OpenSans-Bold.ttf
    - OpenSans-Italic.ttf
    - OpenSans-BoldItalic.ttf
    - Aleo-Bold.ttf
    - Aleo-BoldItalic.ttf
    - Aleo-Italic.ttf
    - Aleo-Light.ttf
    - Aleo-LightItalic.ttf
    - Aleo-Regular.ttf